#!/bin/sh

# This shell script installs and configures Xdebug

pecl install xdebug

cat > ${PHP_INI_DIR}/conf.d/xdebug.ini <<EOL
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.max_nesting_level=1000
EOL